<a href="https://colab.research.google.com/github/AlejRamos/Aprendiendo-Pandas/blob/main/Funcionalidad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

"""
url = https://pandas.pydata.org/docs/user_guide/basics.html
"""

index = pd.date_range("1/1/2000", periods=8)
index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [3]:
"""
Encabezado y Cola
Sirve para ver el encabezado o parte final de una serie de datos
de pandas. Por default se muestran 5 filas, pero también puede 
obtenerse a elección.
"""

serie_larga = pd.Series(np.random.randn(100))

print(serie_larga.head()) #Muestra el encabezado

print(serie_larga.tail(3)) #muestra la cola, solo los ultimos tres elementos

#Aplica también con los DataFrame


0    0.766007
1   -1.398117
2    1.049518
3    0.242958
4    0.248128
dtype: float64
97    1.062484
98    0.844808
99   -0.410258
dtype: float64


In [4]:
"""
Atributos y datos subyacentes
pandas tiene un un numero grandes de atriutos que facilitan el acceso a 
metadatos
"""

index = pd.date_range("1/1/2000", periods=8)

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

print(df)

print(df.shape) #Da la forma, número de filas y columnas respectivamente

print(df.index) #Da los índices,

df.columns = [x.lower() for x in df.columns] #Cambia las columnas por minusculas
#Lo importante en la línea anterior es es el acceso a las columnas
print(df.columns)

print(df)

                   A         B         C
2000-01-01 -1.619713 -0.898281  1.112260
2000-01-02 -0.940848 -0.918760  0.669601
2000-01-03  0.140212 -0.938467  0.813083
2000-01-04 -0.558094  0.023123  0.478864
2000-01-05 -1.482977  1.271223  0.413201
2000-01-06 -2.292497  0.592761  0.935322
2000-01-07  1.716964  0.243417  0.873584
2000-01-08 -0.822124 -0.169496  1.143191
(8, 3)
DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')
Index(['a', 'b', 'c'], dtype='object')
                   a         b         c
2000-01-01 -1.619713 -0.898281  1.112260
2000-01-02 -0.940848 -0.918760  0.669601
2000-01-03  0.140212 -0.938467  0.813083
2000-01-04 -0.558094  0.023123  0.478864
2000-01-05 -1.482977  1.271223  0.413201
2000-01-06 -2.292497  0.592761  0.935322
2000-01-07  1.716964  0.243417  0.873584
2000-01-08 -0.822124 -0.169496  1.143191


In [5]:
"""
Propiedad de array
"""

s.array #Hace un array a la serie s

#De la misma forma podemos acceder a los índices como un array
s.index.array

#Podemos transformarlo en un array de numpy
s.to_numpy()

#O usando
np.asarray(s)

"""
to_numpy() nos da cierta libertad de elegir el tipo de dato, por ejemplo
si consideramos fechas horarios, no podemos trabajar en numpy con esto, 
asi que tenemos dos posibilidades: object-dtype, datatime64[ns]
"""
ser = pd.Series(pd.date_range("2000", periods=2, tz="CET"))
print(ser)

print(ser.to_numpy(dtype=object)) #Tipo objecto

print(ser.to_numpy(dtype="datetime64[ns]"))


0   2000-01-01 00:00:00+01:00
1   2000-01-02 00:00:00+01:00
dtype: datetime64[ns, CET]
[Timestamp('2000-01-01 00:00:00+0100', tz='CET')
 Timestamp('2000-01-02 00:00:00+0100', tz='CET')]
['1999-12-31T23:00:00.000000000' '2000-01-01T23:00:00.000000000']


In [6]:
"""
Si los datos de un DataFrame son de un mismo tipo, DataFrame.to_numpy()
devolvera los datos
"""

print(df.to_numpy())

"""
Solo aplica para datos homogeneos, para aquellos datos heterogeneos
el dtype se ajustará para acomodar los datos involucrados
"""

[[-1.6197129  -0.89828146  1.11225971]
 [-0.94084755 -0.91876025  0.66960064]
 [ 0.1402123  -0.93846688  0.81308301]
 [-0.55809409  0.02312319  0.47886403]
 [-1.48297741  1.27122346  0.41320087]
 [-2.2924966   0.59276075  0.93532224]
 [ 1.71696431  0.24341728  0.87358368]
 [-0.82212403 -0.16949589  1.14319098]]


'\nSolo aplica para datos homogeneos, para aquellos datos heterogeneos\nel dtype se ajustará para acomodar los datos involucrados\n'

In [7]:
"""
Operaciones binarias Flexibles
"""

"""
Comportamiento de coincidencia / transmisión
DataFrame tiene los métodos add(), sub(), mul(), div() y funciones 
relacionadas  radd(), rsub(), … para realizar operaciones binarias.
"""

df1 = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)
print(df1)

row = df1.iloc[1]
print(row)

column = df1["two"]
print(column)

#con sub se sustrae una determinada fila, en este caso columna por columna
print(df1.sub(row, axis="columns"))
#Sustrae determinada fila, fila a fila
print(df1.sub(column, axis="index"))
#El 1 en axis hace lo mismo que columns, y 0 lo que index
print(df1.sub(row, axis=1))

#Usando add, aplica igual pero aquí se agrega
print(df1.add(row, axis="columns"))

#Usando mult(), se multiplica
print(df1.mul(row, axis="columns"))

#Finalmente div(), divide
print(df1.div(row, axis="columns"))

        one       two     three
a  1.384632 -0.300901       NaN
b -0.253354 -0.555348  1.424473
c  0.908533  0.813484 -1.014630
d       NaN -1.236803  1.579523
one     -0.253354
two     -0.555348
three    1.424473
Name: b, dtype: float64
a   -0.300901
b   -0.555348
c    0.813484
d   -1.236803
Name: two, dtype: float64
        one       two     three
a  1.637986  0.254447       NaN
b  0.000000  0.000000  0.000000
c  1.161886  1.368832 -2.439103
d       NaN -0.681456  0.155050
        one  two     three
a  1.685533  0.0       NaN
b  0.301994  0.0  1.979821
c  0.095049  0.0 -1.828114
d       NaN  0.0  2.816327
        one       two     three
a  1.637986  0.254447       NaN
b  0.000000  0.000000  0.000000
c  1.161886  1.368832 -2.439103
d       NaN -0.681456  0.155050
        one       two     three
a  1.131278 -0.856249       NaN
b -0.506707 -1.110696  2.848946
c  0.655179  0.258136  0.409843
d       NaN -1.792151  3.003996
        one       two     three
a -0.350802  0.167105       NaN
b

In [8]:
"""
Más aun, se pueden alinear un nivel de un DataFrame multindexado
con una serie
"""

dfmi = df1.copy()

dfmi.index = pd.MultiIndex.from_tuples(
    [(1, "a"), (1, "b"), (1, "c"), (2, "a")], names=["first", "second"]
)

print(dfmi)
#
print(dfmi.sub(column, axis=0, level="second"))


                   one       two     three
first second                              
1     a       1.384632 -0.300901       NaN
      b      -0.253354 -0.555348  1.424473
      c       0.908533  0.813484 -1.014630
2     a            NaN -1.236803  1.579523
                   one       two     three
first second                              
1     a       1.685533  0.000000       NaN
      b       0.301994  0.000000  1.979821
      c       0.095049  0.000000 -1.828114
2     a            NaN -0.935902  1.880424


In [9]:
"""
A Series también se le aplica la función divmod()
Esta función devuleve floor division, y a su vez la función modulo,
entonces se regresa dos tuplas del mismo tipo.
"""

s = pd.Series(np.arange(10))

#En divmod, la primer variable es la serie a dividir, el segundo entre que
div, res = divmod(s,3)

print(div,res)

print()

dx = pd.Index(np.arange(10))

divx, resx = divmod(dx,3)

print(divx,resx)

#También existe la posibilidad de dividir elemento a elemento

dive, rese = divmod(s,[1,1,2,3,4,5,6,7,8,9])

print(dive, rese)

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int64 0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int64

Int64Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64') Int64Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int64')
0    0
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int64 0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
dtype: int64


In [10]:
"""
Datos Faltantes / operaciones con fill values
Las funciones aritmeticas tienen la opción de ingresar un fill_value,
en modo de sustitución en mas de un valor que falta.
"""

df1

df2 = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(4), index=["a", "b", "c","d"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)

#En este caso df1 tiene dos NaN y df2 solo un
print(df1)
print(df2)

#Ahora al sumarlos
print(df1+df2)
#Observamos que el resultado muestra dos NaN

#Usando un fill_value
print(df1.add(df2,fill_value=0))
#En este caso un NaN, inferior izquierdo en df1 tomo el valor 0

        one       two     three
a  1.384632 -0.300901       NaN
b -0.253354 -0.555348  1.424473
c  0.908533  0.813484 -1.014630
d       NaN -1.236803  1.579523
        one       two     three
a  0.429662  0.495396       NaN
b -1.061184 -0.959562 -0.643073
c  0.739723  0.118317  0.537128
d -0.636306 -3.380374  1.737451
        one       two     three
a  1.814295  0.194495       NaN
b -1.314537 -1.514910  0.781400
c  1.648256  0.931800 -0.477502
d       NaN -4.617178  3.316974
        one       two     three
a  1.814295  0.194495       NaN
b -1.314537 -1.514910  0.781400
c  1.648256  0.931800 -0.477502
d -0.636306 -4.617178  3.316974


In [11]:
"""
Comparaciones binarias
Tenemos también métodos de comparacion, eq, ne, lt, gt, le y ge
cuyo comportamiento es análogo a las operaciones binarias aritmeticas.
El resultado es un booleano
"""

#Comparación de igualdad
print(df1.eq(df1))

#Comparación de desigualdad
print(df1.ne(df1))

#Comparación menor que
print(df1.lt(df2))

#Comparación mayor que
print(df1.gt(df2))

#Comparación menor que, en sentido opuesto
print(df1.le(df2))

#Comparación mayor que, en sentido opuesto
print(df1.ge(df2))

     one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True
     one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False
     one    two  three
a  False   True  False
b  False  False  False
c  False  False   True
d  False  False   True
     one    two  three
a   True  False  False
b   True   True   True
c   True   True  False
d  False   True  False
     one    two  three
a  False   True  False
b  False  False  False
c  False  False   True
d  False  False   True
     one    two  three
a   True  False  False
b   True   True   True
c   True   True  False
d  False   True  False


In [12]:
"""
Reducciones booleanas
Se pueden aplicar reducciones, empty, any(), all() y bool()
como forma de resumir. El resultado es un boolean
"""

#Vacio? Nos dice si un conjunto es vacio
df1.empty

#Todos los elementos, indica si todos cumplen cierta condición
#En las filas del DataFrame
print((df1>1).all())

#Alguno, indica si algun elemento de las filas del DF cumple la condición
print((df1>0).any())

#Se puede reducir aun más el resultado a un solo booleano
print((df1>0).any().any())

one      False
two      False
three    False
dtype: bool
one      True
two      True
three    True
dtype: bool
True


In [13]:
"""
Comparación si objetos son equivalentes
Estamos de acuerdo que existen varias formas de llegar a un mismo resultado
Ya vimos que con comparaciones booleanas se puede afirmar o negar cierta
condición, sin embargo cuando se tata de equivalencias, es decir ==, estos 
no funcionan, por tanto se usa otro método
"""

print(df1 + df1 == df1*2 )
#Como resultado aparecera un DataFrame que entrada a entrada dice si es o no
#equivalente. Nótese que aparecen False, dado que NaN no se comparan como iguales
print(np.NaN == np.NaN)

print((df1 + df1 == df1*2).all())
#En este devuelve una Serie, pero no afirma la equivalencia

#Para poder hacer comparaciones los DataFrame tienen que ser del mismo tipo 
# y del mismo orden 
df3 = pd.DataFrame({"col": ["foo", 0, np.nan]})

df4 = pd.DataFrame({"col": [np.nan, 0, "foo"]}, index=[2, 1, 0])

print(df1.equals(df2))


     one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True
False
one      False
two       True
three    False
dtype: bool
False


In [14]:
"""
Comparando como objetos array
Puede realizar cómodamente comparaciones a nivel de elementos al comparar 
una estructura de datos pandas con un valor escalar
"""

#Ésta sería la forma convencional en pandas
print(pd.Series(["foo", "bar", "baz"]) == "foo")

#Si queremos compararlo como un elemento array
print(pd.Index(["foo", "bar", "baz"]) == "foo")

"""
Pandas también maneja comparaciones de tipos matrices de la misma
magnitud
"""

#En el siguiente ejemplo comparamos una Serie de panda con un Index
print(pd.Series(["foo", "bar", "baz"]) == pd.Index(["foo", "bar", "qux"]))

#El siguiente ejemplo compara una Serie de panda con un array de numpy
print(pd.Series(["foo", "bar", "baz"]) == np.array(["foo", "bar", "qux"]))

#Al intentar comparar dos onjetos de distinto tamaño habra error

#Como nota, es distinto la comparacion de numpy 
print(np.array([1, 2, 3]) == np.array([2]))

#Y retornará falso cuando la comparación no se pueda hacer
print(np.array([1, 2, 3]) == np.array([1, 2]))

0     True
1    False
2    False
dtype: bool
[ True False False]
0     True
1     True
2    False
dtype: bool
0     True
1     True
2    False
dtype: bool
[False  True False]
False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:30: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


In [24]:
"""
Combinacion de conjuntos superpuestos
Un problema al que nos podemos enfrentar es el combinar dos conjuntos
de datos, en done queremos darle prioridad a uno por cualquier razon, 
esta combinación de datos se puede hacer entre dos datos de distinto
tamaño.
"""

df5 = pd.DataFrame(
    {"A": [1.0, np.nan, 3.0, 5.0, np.nan], "B": [np.nan, 2.0, 3.0, np.nan, 6.0]}
)

df6  = pd.DataFrame(
    {
        "A": [5.0, 2.0, 4.0, np.nan, 3.0, 7.0],
        "B": [np.nan, np.nan, 3.0, 4.0, 6.0, 8.0],
    }
)

#Ambos objetos son un Data Frame de distintos tamaños

print(df5)

print(df6)

#En este ejemplo se dará prioridad a df5
df5.combine_first(df6)

"""
Nótese que en los elementos NaN, aunque tenga prioridad df5, los elementos
se combinan de tal forma que aparezcan la menor cantidad posible de NaN.
"""

     A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0
     A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0


'\nNótese que en los elementos NaN, aunque tenga prioridad df5, los elementos\nse combinan de tal forma que aparezcan la menor cantidad posible de NaN.\n'